import type { KpiDefinition } from '@/types/kpi';

export const DEFAULT_KPI_DEFINITIONS: KpiDefinition[] = [
  {
    id: 'avg_ticket',
    name: 'Average Ticket',
    description: 'Total revenue from completed opportunity jobs ÷ number of completed opportunity jobs (exclude warranty, no-charge)',
    formula: 'avg_ticket',
    dataSource: 'jobs',
    target: 500,
    displayFormat: 'currency',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'avg_opportunity',
    name: 'Average Opportunity',
    description: 'Total revenue from ALL completed jobs ÷ total number of completed jobs',
    formula: 'avg_opportunity',
    dataSource: 'jobs',
    target: 400,
    displayFormat: 'currency',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'conversion_rate',
    name: 'Conversion Rate',
    description: 'Number of jobs where invoice > $0 ÷ total opportunities assigned to tech × 100',
    formula: 'conversion_rate',
    dataSource: 'jobs',
    target: 75,
    displayFormat: 'percentage',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'avg_repair_ticket',
    name: 'Avg Repair Ticket',
    description: 'Revenue from repair/service jobs ÷ count of those jobs',
    formula: 'avg_repair_ticket',
    dataSource: 'jobs',
    target: 350,
    displayFormat: 'currency',
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'avg_install_ticket',
    name: 'Avg Install Ticket',
    description: 'Revenue from installation jobs ÷ count of those jobs',
    formula: 'avg_install_ticket',
    dataSource: 'jobs',
    target: 2000,
    displayFormat: 'currency',
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'new_doors_installed',
    name: 'New Doors Installed',
    description: 'Count of completed jobs with type "Door Install" or "Door + Opener Install"',
    formula: 'new_doors_installed',
    dataSource: 'jobs',
    target: 10,
    displayFormat: 'count',
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 'total_opportunities',
    name: 'Total Opportunities',
    description: 'Count of all jobs assigned to the tech in the selected time period',
    formula: 'total_opportunities',
    dataSource: 'jobs',
    target: 40,
    displayFormat: 'count',
    isActive: true,
    sortOrder: 7,
  },
  {
    id: 'five_star_reviews',
    name: '5-Star Google Reviews',
    description: 'Count of 5-star reviews attributed to this tech',
    formula: 'five_star_reviews',
    dataSource: 'reviews',
    target: 5,
    displayFormat: 'count',
    isActive: true,
    sortOrder: 8,
  },
  {
    id: 'protection_plan_sales',
    name: 'Protection Plan Sales',
    description: 'Count of memberships/service agreements sold by this tech',
    formula: 'protection_plan_sales',
    dataSource: 'jobs',
    target: 5,
    displayFormat: 'count',
    isActive: true,
    sortOrder: 9,
  },
  {
    id: 'commission',
    name: 'Commission',
    description: 'Total commission earned in the selected period',
    formula: 'commission',
    dataSource: 'commission_records',
    target: 5000,
    displayFormat: 'currency',
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 'callback_rate',
    name: 'Callback Rate',
    description: 'Number of warranty/callback jobs ÷ total completed jobs × 100 (lower is better)',
    formula: 'callback_rate',
    dataSource: 'jobs',
    target: 5,
    displayFormat: 'percentage',
    isActive: true,
    invertedStatus: true,
    sortOrder: 11,
  },
  {
    id: 'avg_options_per_ticket',
    name: 'Options / Ticket',
    description: 'Average HCP estimate options written per ticket (excludes warranty/callbacks). Higher = techs presenting more pricing choices on every opportunity.',
    formula: 'avg_options_per_ticket',
    dataSource: 'estimates+jobs',
    target: 3.0,
    displayFormat: 'decimal',
    isActive: true,
    sortOrder: 12,
  },
];
