import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <div className="min-h-screen flex items-center justify-center">
      <p className="text-gray-600">
        3B Holdings Dashboard — UI to be generated by Claude Design.
      </p>
    </div>
  </React.StrictMode>,
);
