<?php
declare(strict_types=1);

/**
 * Per-city editorial content for location pages.
 *
 * This file is the ONLY place location page copy is authored. Templates and
 * renderers read from it; they are not edited to add or change city copy.
 *
 * 'completedJobs' is real data from completed Twins jobs, aggregated by service
 * ZIP and verified 2026-07-21. It is null where a city shares its ZIPs with
 * Madison and no separable per-city figure exists, and null for cities with no
 * job history yet. When it is null, the copy must not cite any job number.
 *
 * 'metro' selects the NAP and phone shown on the page. It is not editorial and
 * must not be changed while writing copy.
 *
 * Empty 'intro', 'localNotes' and 'faq' are unwritten. Empty is valid and
 * renders the shared default; a page is never blocked on missing copy.
 */

return [
    'madison' => [
        'label' => 'Madison',
        'metro' => 'madison',
        'completedJobs' => null,  // shares ZIPs with Madison; per-city count not separable
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'verona' => [
        'label' => 'Verona',
        'metro' => 'madison',
        'completedJobs' => 372,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'sun-prairie' => [
        'label' => 'Sun Prairie',
        'metro' => 'madison',
        'completedJobs' => 286,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'middleton' => [
        'label' => 'Middleton',
        'metro' => 'madison',
        'completedJobs' => 263,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'oregon' => [
        'label' => 'Oregon',
        'metro' => 'madison',
        'completedJobs' => 101,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'deforest' => [
        'label' => 'DeForest',
        'metro' => 'madison',
        'completedJobs' => 91,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'waunakee' => [
        'label' => 'Waunakee',
        'metro' => 'madison',
        'completedJobs' => 91,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'mcfarland' => [
        'label' => 'McFarland',
        'metro' => 'madison',
        'completedJobs' => 67,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'cottage-grove' => [
        'label' => 'Cottage Grove',
        'metro' => 'madison',
        'completedJobs' => 60,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'pardeeville' => [
        'label' => 'Pardeeville',
        'metro' => 'madison',
        'completedJobs' => 41,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'baraboo' => [
        'label' => 'Baraboo',
        'metro' => 'madison',
        'completedJobs' => 40,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'deerfield' => [
        'label' => 'Deerfield',
        'metro' => 'madison',
        'completedJobs' => 40,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'janesville' => [
        'label' => 'Janesville',
        'metro' => 'madison',
        'completedJobs' => 72,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'stoughton' => [
        'label' => 'Stoughton',
        'metro' => 'madison',
        'completedJobs' => 36,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'portage' => [
        'label' => 'Portage',
        'metro' => 'madison',
        'completedJobs' => 28,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'mount-horeb' => [
        'label' => 'Mount Horeb',
        'metro' => 'madison',
        'completedJobs' => 28,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'belleville' => [
        'label' => 'Belleville',
        'metro' => 'madison',
        'completedJobs' => 23,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'edgerton' => [
        'label' => 'Edgerton',
        'metro' => 'madison',
        'completedJobs' => 19,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'reedsburg' => [
        'label' => 'Reedsburg',
        'metro' => 'madison',
        'completedJobs' => 18,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'evansville' => [
        'label' => 'Evansville',
        'metro' => 'madison',
        'completedJobs' => 15,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'monroe' => [
        'label' => 'Monroe',
        'metro' => 'madison',
        'completedJobs' => 14,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'cross-plains' => [
        'label' => 'Cross Plains',
        'metro' => 'madison',
        'completedJobs' => 12,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'cambridge' => [
        'label' => 'Cambridge',
        'metro' => 'madison',
        'completedJobs' => 11,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'windsor' => [
        'label' => 'Windsor',
        'metro' => 'madison',
        'completedJobs' => 11,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'brooklyn' => [
        'label' => 'Brooklyn',
        'metro' => 'madison',
        'completedJobs' => 10,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'rio' => [
        'label' => 'Rio',
        'metro' => 'madison',
        'completedJobs' => 10,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'new-glarus' => [
        'label' => 'New Glarus',
        'metro' => 'madison',
        'completedJobs' => 10,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'fall-river' => [
        'label' => 'Fall River',
        'metro' => 'madison',
        'completedJobs' => 10,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'beloit' => [
        'label' => 'Beloit',
        'metro' => 'madison',
        'completedJobs' => 10,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'marshall' => [
        'label' => 'Marshall',
        'metro' => 'madison',
        'completedJobs' => 9,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'columbus' => [
        'label' => 'Columbus',
        'metro' => 'madison',
        'completedJobs' => 9,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'sauk-city' => [
        'label' => 'Sauk City',
        'metro' => 'madison',
        'completedJobs' => 8,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'milton' => [
        'label' => 'Milton',
        'metro' => 'madison',
        'completedJobs' => 8,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'lodi' => [
        'label' => 'Lodi',
        'metro' => 'madison',
        'completedJobs' => 8,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'barneveld' => [
        'label' => 'Barneveld',
        'metro' => 'madison',
        'completedJobs' => 7,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'fort-atkinson' => [
        'label' => 'Fort Atkinson',
        'metro' => 'madison',
        'completedJobs' => 6,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'prairie-du-sac' => [
        'label' => 'Prairie du Sac',
        'metro' => 'madison',
        'completedJobs' => 4,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'watertown' => [
        'label' => 'Watertown',
        'metro' => 'madison',
        'completedJobs' => 16,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'fitchburg' => [
        'label' => 'Fitchburg',
        'metro' => 'madison',
        'completedJobs' => null,  // shares ZIPs with Madison; per-city count not separable
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'monona' => [
        'label' => 'Monona',
        'metro' => 'madison',
        'completedJobs' => null,  // shares ZIPs with Madison; per-city count not separable
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'milwaukee' => [
        'label' => 'Milwaukee',
        'metro' => 'milwaukee',
        'completedJobs' => 1,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'wauwatosa' => [
        'label' => 'Wauwatosa',
        'metro' => 'milwaukee',
        'completedJobs' => null,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'waukesha' => [
        'label' => 'Waukesha',
        'metro' => 'milwaukee',
        'completedJobs' => 1,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'brookfield' => [
        'label' => 'Brookfield',
        'metro' => 'milwaukee',
        'completedJobs' => null,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'new-berlin' => [
        'label' => 'New Berlin',
        'metro' => 'milwaukee',
        'completedJobs' => null,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'greenfield' => [
        'label' => 'Greenfield',
        'metro' => 'milwaukee',
        'completedJobs' => null,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
    'oak-creek' => [
        'label' => 'Oak Creek',
        'metro' => 'milwaukee',
        'completedJobs' => null,
        'intro' => '',
        'localNotes' => '',
        'faq' => [],
    ],
];
